### ISSUE TITLE
I'm using Home Assistant Core - how do I install?

### ISSUE THREAD

**Issue by ThermoMan** [tlskinneriv/hassio-addons#15]
The linked instructions from 
https://github.com/tlskinneriv/hassio-addons/blob/master/README.md
send me to 
https://www.home-assistant.io/common-tasks/os#installing-third-party-add-ons
which are instructions for HAOS, not HA Core.  Core does not have the "Add-ons" feature.

Do I just download the code and stuff it somewhere in the folder?
My Home Assistant is on a VM running Ubuntu with many other services.  HA is running under Docker.
HA Core 2024.6.2 
HACS 
Ambient Weather Station - Local v1.2.0 ( Installed with the click button on your other page: https://github.com/tlskinneriv/awnet_local )
My ambient Weather station is model WS-2902D

Also, I'm assuming I need to open port 7080 in my firewall (ufw) so that the Ambient Weather device can send data in.

**Comment by tlskinneriv** [comment]
Right now I don't have instructions for anything other than HAOS. In theory as long as you have an API token and modify the Python script in the container with the correct URL, it should work. Right now, the Python script is tuned to use a built-in supervisor token and URL from the add-on. 

I'll take a look this weekend and see if I can put together a modified script and some instructions.

**Comment by ThermoMan** [comment]
> I'll take a look this weekend and see if I can put together a modified script and some instructions.
Please and thank you!

I'm really trying to avoid a cloud dependency and your code looks like it fits the bill!

**Comment by tlskinneriv** [comment]
See https://github.com/tlskinneriv/hassio-addons/blob/master/awnet/DOCS.md#non-ha-os-options for details.

**Comment by ThermoMan** [comment]
Bless you sir!
