### ISSUE TITLE
Failed to send {}

### ISSUE THREAD

**Issue by SARuiner** [tlskinneriv/hassio-addons#3]
I am trying to get your addon to work with my system and it is failing.  Here is the output in the log:

`Failed to send {} to http://supervisor/core/api/services/awnet_local/update with headers {'Authorization': 'Bearer <redacted>', 'content-type': 'application/json'}; b'500 Internal Server Error\n\nServer got itself in trouble'
192.168.50.58 - - [18/Mar/2022 08:56:45] "GET stationtype=AMBWeatherV4.3.2&PASSKEY=F4:CF:A2:CD:A0:1A&dateutc=2022-03-18+13:56:45&tempinf=73.6&battin=1&humidityin=44&baromrelin=28.766&baromabsin=28.766&tempf=49.6&battout=1&humidity=98&winddir=23&winddir_avg10m=22&windspeedmph=3.4&windspdmph_avg10m=2.7&windgustmph=3.4&maxdailygust=5.8&hourlyrainin=0.047&eventrainin=0.039&dailyrainin=0.319&weeklyrainin=0.319&monthlyrainin=1.000&yearlyrainin=2.457&solarradiation=16.39&uv=0&batt_co2=1 HTTP/1.1" 200 0`

I am currently running Home Assistant OS on an Intel Nuc.  I am using an Ambient Weather station (WS-2000).  The values above are accurate but they aren't getting passed to HA (all of them say "Unavailable").

**Comment by tlskinneriv** [comment]
Hi! Please see https://github.com/tlskinneriv/hassio-addons/issues/1#issuecomment-1024668239 to see if that fixes your problem. I haven't gotten around to updating the documentation for that yet to make it more clear.

**Comment by SARuiner** [comment]
Ok, I'm dying from laughter over here.  I thought the '?' in the configuration was like "just put whatever, we don't know".  I didn't realize it was an actual question-mark.

I did that and it fixed it.  You are amazing!

**Comment by ziptbm** [comment]
@tlskinneriv I've run into this issue as well.  I literally put only a question mark into the path per the readme, but I'm still getting this same issue.  Here's what I'm seeing in the log and I've sanitized a bit with "x."   Any ideas about what else I'm doing wrong?

I'm using a WS-5000-IP that's fully updated on firmware.


`Failed to send {"MAC": "xx:xx:xx:xx:xx:xx"} to http://supervisor/core/api/services/awnet_local/update with headers {'Authorization': 'Bearer <redacted>', 'content-type': 'application/json'}; b'500 Internal Server Error\n\nServer got itself in trouble' 10.0.0.27 - - [30/Jun/2022 21:07:58] "GET ?MAC=xx:xx:xx:xx:xx:xx" 200 0`

**Comment by tlskinneriv** [comment]
@ziptbm Latest release should fix your issue. Evidently the WS-5000 device send malformed requests. Sorry I missed your comment and it's taken so long to get an update!
