### ISSUE TITLE
Latest base image breaks addon

### ISSUE THREAD

**Issue by Doonga** [tlskinneriv/hassio-addons#5]
Hi, please see here: https://community.home-assistant.io/t/latest-base-image-with-s6-overlay-v3-breaks-add-on/421570 and here: https://community.home-assistant.io/t/hello-world-example-addon-from-developer-docs-stopped-working-s6-overlay-issue/421486

It looks like something changed that's causing an issue with some addons including this one. It'll only show this in the log then fail to run: s6-overlay-suexec: fatal: can only run as pid 1

I tried forking this repo and adding the "init": false to the config.json which does fix it, but I'm not sure if that's the right way to do it.

I figured I'd pass that along if you hadn't seen it yet.
Thanks!

**Comment by tlskinneriv** [comment]
Thanks for the heads up! Will add todo. PR welcome if you do end up finding out whatever the "right" way is before I get a chance to.
