### ISSUE TITLE
Feature Request - aarch64 image

### ISSUE THREAD

**Issue by ObiWanCanOweMe** [tlskinneriv/hassio-addons#9]
Hi,

I'm moving my HA install to a Raspberry Pi 4 and there doesn't seem to be an aarch64 Docker image:

![image](https://user-images.githubusercontent.com/3590240/185733507-2847e5e2-d04f-4c11-bc85-e2598f8a752e.png)

Is that something that can be provided?

Thanks!

**Comment by tlskinneriv** [comment]
Will do some research on this to see how this is done. May require having a separate add-on folder here to support the differing Dockerfile. Should have some time to look at this tomorrow. Don't see why it shouldn't work since all of the code is common Python.
